---
- hosts: local
  gather_facts: no
  tasks:
    - name: load ssh key
      shell: |
          eval `ssh-agent -s`
          ssh-add ~/.ssh/id_rsa
- hosts: test
  gather_facts: no
  vars:
    key: "{{ lookup('file', '~/.ssh/id_rsa') }}"
  
  tasks:
    - name: Ensure .ssh directory exists.
      file:
        path: /var/www/.ssh
        state: directory
        mode: 0700
      become: yes

    - name: Put key on remote server
      copy:
        content: "{{ key }}"
        dest: /var/www/.ssh/deploy_key
        mode: 0600
      become: yes

    - name: Remove current git repo
      file:
        state: absent
        path: "cse356-milestone1.git/"
      become: yes

    - name: Clone github repo
      git: 
        repo: git@github.com:mvandenburgh/cse356-milestone1
        version: master
        accept_hostkey: yes
        dest: /home/ubuntu/cse356-milestone1
        key_file: /var/www/.ssh/deploy_key
      become: yes

    - name: install MySQL Server
      apt:
        name: mysql-server
        state: present
        update_cache: yes
      become: yes
     
    - name: Start the MySQL service
      sudo: yes
      service: 
        name: mysql 
        state: started
        enabled: true

    - name: Install python-mysqldb
      apt:
        name: python-mysqldb
        state: present
        update_cache: yes
      become: yes
    - name: Install PyMySql
      apt:
        name: pymysql
        state: present
        update_cache: yes
      become: yes

    - name: update mysql root password for all root accounts
      sudo: yes
      mysql_user: 
        name: root 
        host: "localhost" 
        password: "mike"
        login_user: root
        login_password: ""
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
      - "test"
      - 127.0.0.1
      - 1
      - localhost
    
    - include: ./nginx.yml
    - include: ./mail.yml
    - include: ./mongo.yml
    - include: ./nodejs.yml
